'use strict';
const $=id=>document.getElementById(id),M=CascadiaModel,D=CASCADIA_DATA;
const formIDs=['magnitude','segment','slip','hypocenter','rise','ruptureSpeed','resolution'];
const ink='#dce9e9',muted='#97b3c0',gridColor='#284450',stationColors=['#e7bf83','#c0b9e9','#94d5a6','#75dcee','#e5a2bb','#a4bad3'];
let result=null,params=null,selected=3,time=1200,playing=false,layer='wave',worker=null,runID=0,firstRun=true,last=0,lastDraw=0;
let zoom=1,panX=0,panY=0,drag=null,view=null,tooltip='',custom=null,workerURL=null;
const terrain=document.createElement('canvas'),landOnly=document.createElement('canvas'),waveRaster=document.createElement('canvas');
const contourSets=[],raw=M.unpack(D),terrainCtx=terrain.getContext('2d'),landCtx=landOnly.getContext('2d');
function settings(){return Object.fromEntries(formIDs.map(id=>[id,['segment','slip','resolution'].includes(id)?$(id).value:+$(id).value]));}
function formatTime(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');}
function labels(){$('magnitudeOut').textContent=(+$('magnitude').value).toFixed(1)+' Mw';$('hypocenterOut').textContent=$('hypocenter').value+'%';}
function lerp(a,b,t){return a+(b-a)*t;}
function palette(stops,v){let i=0;while(i<stops.length-2&&v>stops[i+1][0])i++;const a=stops[i],b=stops[i+1],t=Math.max(0,Math.min(1,(v-a[0])/(b[0]-a[0])));return a[1].map((x,k)=>lerp(x,b[1][k],t));}
function initTerrain(){terrain.width=landOnly.width=D.nx;terrain.height=landOnly.height=D.ny;const img=terrainCtx.createImageData(D.nx,D.ny),land=landCtx.createImageData(D.nx,D.ny);
 const stops=[[-6000,[7,28,45]],[-3500,[13,48,66]],[-1800,[18,63,77]],[-200,[39,86,96]],[0,[70,106,109]],[1,[49,73,67]],[500,[65,87,73]],[1600,[82,98,86]],[3000,[140,147,132]],[4500,[203,203,178]]];
 for(let j=0;j<D.ny;j++)for(let i=0;i<D.nx;i++){const k=j*D.nx+i,z=raw[k],dzx=(raw[j*D.nx+Math.min(i+1,D.nx-1)]-raw[j*D.nx+Math.max(i-1,0)])/3000,dzy=(raw[Math.min(j+1,D.ny-1)*D.nx+i]-raw[Math.max(j-1,0)*D.nx+i])/4500,light=Math.max(.52,Math.min(1.3,.95-.5*dzx+.6*dzy)),col=palette(stops,z),o=((D.ny-1-j)*D.nx+i)*4;
  for(let a=0;a<3;a++){img.data[o+a]=col[a]*light;land.data[o+a]=col[a]*light;}img.data[o+3]=255;land.data[o+3]=z>=0?255:0;
 }
 terrainCtx.putImageData(img,0,0);landCtx.putImageData(land,0,0);
 for(const level of [0,-200,-1000,-3000]){const lines=[];for(let j=0;j<D.ny-1;j++)for(let i=0;i<D.nx-1;i++){const corners=[[i,j],[i+1,j],[i+1,j+1],[i,j+1]],vs=corners.map(([x,y])=>raw[y*D.nx+x]),pts=[];for(let e=0;e<4;e++){const f=(e+1)%4;if((vs[e]<level)!==(vs[f]<level)){const t=(level-vs[e])/(vs[f]-vs[e]);pts.push([D.lon0+lerp(corners[e][0],corners[f][0],t)*D.step,D.lat0+lerp(corners[e][1],corners[f][1],t)*D.step]);}}if(pts.length===2)lines.push(pts);else if(pts.length===4){lines.push([pts[0],pts[1]],[pts[2],pts[3]]);}}
 contourSets.push({level,lines});}
}
function setupCanvas(id){const el=$(id),r=el.getBoundingClientRect(),d=Math.min(2,window.devicePixelRatio||1);if(el.width!==Math.round(r.width*d)||el.height!==Math.round(r.height*d)){el.width=Math.round(r.width*d);el.height=Math.round(r.height*d);}const c=el.getContext('2d');c.setTransform(d,0,0,d,0,0);c.clearRect(0,0,r.width,r.height);return [c,r.width,r.height];}
function line(c,pts,color,width=1,dash=[]){if(!pts.length)return;c.beginPath();pts.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.strokeStyle=color;c.lineWidth=width;c.setLineDash(dash);c.stroke();c.setLineDash([]);}
function txt(c,s,x,y,color=muted,size=10,weight=400){c.font=`${weight} ${size}px -apple-system,BlinkMacSystemFont,sans-serif`;c.fillStyle=color;c.fillText(s,x,y);}
function sampleFrame(k){if(!result)return 0;const f=Math.min(result.frames.length-1,Math.floor(time/result.sample)),t=time/result.sample-f,a=result.frames[f][k]*result.frameScales[f],b=f<result.frames.length-1?result.frames[f+1][k]*result.frameScales[f+1]:a;return lerp(a,b,t);}
function selectedGauge(){return custom||result.gauges[selected];}
function seriesFor(g){return custom?result.frames.map((f,i)=>f[g.index]*result.frameScales[i]):result.series[selected];}
function updateWaveRaster(){if(!result)return;const g=result.grid;if(waveRaster.width!==g.nx){waveRaster.width=g.nx;waveRaster.height=g.ny;}const ctx=waveRaster.getContext('2d'),im=ctx.createImageData(g.nx,g.ny);
 for(let j=0;j<g.ny;j++)for(let i=0;i<g.nx;i++){const k=j*g.nx+i;if(layer!=='source'&&!g.h[k])continue;const v=layer==='peak'?result.peaks[k]:layer==='source'?result.deformation[k]:sampleFrame(k),max=layer==='source'?10:layer==='peak'?6:4,a=Math.min(1,Math.abs(v)/max);if(a<.002)continue;let col=layer==='peak'?[255,lerp(105,212,a),lerp(90,140,a)]:v>0?[255,lerp(120,226,a),lerp(101,156,a)]:[lerp(51,113,a),lerp(148,220,a),lerp(195,242,a)];const o=((g.ny-1-j)*g.nx+i)*4;for(let z=0;z<3;z++)im.data[o+z]=col[z];im.data[o+3]=Math.min(245,(a**.52)*275);}
 ctx.putImageData(im,0,0);
}
function drawMap(){const [c,w,h]=setupCanvas('map');const s=Math.min((w-12)/(12.5*.7),(h-140)/12.6)*zoom,cx=w*.5+panX,cy=h*.5+16+panY;
 const P=(lon,lat)=>[cx+(lon+127.05)*s*.7,cy-(lat-45.65)*s];view={P,s,cx,cy,w,h};
 const rectImage=(img,g)=>{const a=P(g.lon0-g.step/2,g.lat0+(g.ny-.5)*g.step),b=P(g.lon0+(g.nx-.5)*g.step,g.lat0-g.step/2);c.drawImage(img,a[0],a[1],b[0]-a[0],b[1]-a[1]);};
 c.fillStyle='#092230';c.fillRect(0,0,w,h);rectImage(terrain,D);
 for(let lat=40;lat<=52;lat+=2){line(c,[P(-135,lat),P(-120,lat)],'#8eb7c113',.7);const p=P(-133,lat);if(p[1]>110&&p[1]<h-110)txt(c,lat+'°N',Math.max(12,p[0]),p[1]-4,'#99b5bd80',8);}
 for(let lon=-132;lon<=-122;lon+=2)line(c,[P(lon,38),P(lon,53)],'#8eb7c110',.7);
 if(result){updateWaveRaster();rectImage(waveRaster,result.grid);if(layer!=='source')rectImage(landOnly,D);}
 for(const set of contourSets){c.beginPath();for(const pair of set.lines){c.moveTo(...P(...pair[0]));c.lineTo(...P(...pair[1]));}c.strokeStyle=set.level===0?'#92bab899':'#a3c2c21c';c.lineWidth=set.level===0?.8:.45;c.stroke();}
 if(result){for(const f of result.geo.faults){const fraction=M.rise(time,f.delay,params.rise);c.beginPath();f.geo.corners.map(p=>P(...p)).forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();c.fillStyle=`rgba(255,198,134,${layer==='source'?.02:.015+fraction*.075})`;c.fill();c.strokeStyle=fraction>0?'#ffd098bb':'#cfb08766';c.lineWidth=.7;c.stroke();}
 const epi=P(...result.geo.hypo);c.beginPath();c.arc(...epi,5,0,Math.PI*2);c.fillStyle='#ffcf96';c.fill();c.beginPath();c.arc(...epi,10,0,Math.PI*2);c.strokeStyle='#ffcf96bb';c.stroke();
 const sites=[...result.gauges];if(custom)sites.push(custom);sites.forEach((g,i)=>{const p=P(g.lon,g.lat),active=custom?g===custom:i===selected;c.beginPath();c.arc(...p,active?5:3,0,Math.PI*2);c.fillStyle=active?'#d3ffed':'#d1e8e9';c.fill();c.strokeStyle='#102633';c.lineWidth=1.5;c.stroke();if(active){c.beginPath();c.arc(...p,10,0,Math.PI*2);c.strokeStyle='#a7e9cd';c.lineWidth=1;c.stroke();}const label=g.name;c.font=`${active?600:400} 10px -apple-system,sans-serif`;const tw=c.measureText(label).width;const px=Math.min(w-tw-8,p[0]+12);c.fillStyle='#071c28c9';c.fillRect(px-3,p[1]-9,tw+6,16);txt(c,label,px,p[1]+3,active?'#d6ffed':'#cfdddd',10,active?600:400);});
 const station=selectedGauge(),left=P(-131,station.lat),right=P(station.lon,station.lat);line(c,[left,right],'#b2e1df80',.8,[3,5]);}
 for(const [label,lon,lat] of [['VANCOUVER ISLAND',-126.3,49.35],['WASHINGTON',-123.1,47.55],['OREGON',-122.3,44.8],['CALIFORNIA',-122.7,40.7]]){const p=P(lon,lat);c.save();if(label==='VANCOUVER ISLAND'){c.translate(...p);c.rotate(-.75);txt(c,label,0,0,'#d0d6c788',8);}else txt(c,label,p[0],p[1],'#d0d6c77f',8);c.restore();}
 const ocean=P(-131.6,45.2);txt(c,'P A C I F I C',ocean[0],ocean[1],'#a7cbda66',11);txt(c,'O C E A N',ocean[0]+5,ocean[1]+18,'#a7cbda66',11);
 const topfade=c.createLinearGradient(0,0,0,108);topfade.addColorStop(0,'#071a25c9');topfade.addColorStop(1,'#071a2500');c.fillStyle=topfade;c.fillRect(0,0,w,108);
 const scalew=200000/M.LM*s;line(c,[[w-160,h-110],[w-160+scalew,h-110]],'#c4d9df',1.4);txt(c,'200 km',w-160,h-117,'#bacbd0',9);txt(c,'N ↑',w-37,125,'#d7e7e8',10);}
function updateStations(){if(!result)return;$('stations').innerHTML=result.gauges.map((g,i)=>`<button class="station" data-station="${i}" aria-pressed="${!custom&&i===selected}"><i></i><span>${g.name}</span><small>${result.peaks[g.index].toFixed(2)} m</small></button>`).join('');$('stations').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=+b.dataset.station;custom=null;updateStations();updateSummary();draw();});$('compareKey').innerHTML=result.gauges.map((g,i)=>`<span style="color:${stationColors[i]}"><i style="background:${stationColors[i]}"></i>${g.name}</span>`).join('');}
function updateSummary(){if(!result)return;const g=selectedGauge(),trace=seriesFor(g);$('stationName').textContent=g.name+(custom?'':' offshore');$('stationMeta').textContent=`${g.lat.toFixed(3)}° N · ${Math.abs(g.lon).toFixed(3)}° W · ${Math.round(g.depth)} m depth`;$('current').innerHTML=(sampleFrame(g.index)>=0?'+':'')+sampleFrame(g.index).toFixed(2)+' <span>m</span>';$('peak').innerHTML=result.peaks[g.index].toFixed(2)+' <span>m</span>';const a=result.arrivals[g.index];$('arrival').innerHTML=a<0?'—':(a/60).toFixed(1)+' <span>min</span>';const k=trace.reduce((a,v,i)=>Math.abs(v)>Math.abs(trace[a])?i:a,0);$('peakTime').textContent=`Largest sampled excursion at ${(k*result.sample/60).toFixed(1)} min`;$('stationLimit').textContent=result.peaks[g.index]/g.depth>.1?'This cell exceeds the small-amplitude assumption. Its water levels are unreliable; no inundation is modeled.':'Offshore water level is not wave runup, flood depth, or a safe evacuation interval.';$('sectionTitle').textContent='The seafloor off '+(custom?'your point':g.name);}
function drawChart(){const [c,w,h]=setupCanvas('chart');if(!result)return;const l=42,r=w-12,t=15,b=h-27,max=Math.max(.5,...result.gauges.map(g=>result.peaks[g.index]),custom?result.peaks[custom.index]:0)*1.13,x=s=>l+s/result.end*(r-l),y=v=>(t+b)/2-v/max*(b-t)/2;
 for(const v of [-max,0,max]){line(c,[[l,y(v)],[r,y(v)]],gridColor,.7);txt(c,v.toFixed(1),4,y(v)+3,muted,9);}txt(c,'m',5,9,muted,9);
 for(const m of [0,30,60,90,120,150,180]){line(c,[[x(m*60),t],[x(m*60),b]],'#1e3743',.6);txt(c,m+'',x(m*60)-7,h-10,muted,9);}
 for(let z=0;z<result.gauges.length;z++){if(z===selected&&!custom)continue;line(c,result.series[z].map((v,i)=>[x(i*result.sample),y(v)]),stationColors[z]+'88',.85);}
 if(!custom)line(c,result.series[selected].map((v,i)=>[x(i*result.sample),y(v)]),stationColors[selected],2.1);else line(c,seriesFor(custom).map((v,i)=>[x(i*result.sample),y(v)]),'#ddffe8',2);
 line(c,[[x(time),t],[x(time),b]],'#ffcd98',1,[3,3]);const q=selectedGauge();c.beginPath();c.arc(x(time),y(sampleFrame(q.index)),3.5,0,Math.PI*2);c.fillStyle='#e7fff2';c.fill();}
function drawSection(){const [c,w,h]=setupCanvas('section');if(!result)return;const g=selectedGauge(),grid=result.grid,row=Math.round((g.lat-grid.lat0)/grid.step),l=45,r=w-14,mid=65,b=h-27,left=Math.max(0,Math.min(Math.round((-131-grid.lon0)/grid.step),g.index%grid.nx-15)),right=Math.min(grid.nx-1,Math.max(g.index%grid.nx+3,left+30)),x=i=>l+(i-left)/(right-left)*(r-l);let depth=1000,max=.2;for(let i=left;i<=right;i++){depth=Math.max(depth,grid.h[row*grid.nx+i]);max=Math.max(max,Math.abs(sampleFrame(row*grid.nx+i)));}const yd=d=>mid+14+d/depth*(b-mid-14);
 c.fillStyle='#163d4e';c.fillRect(l,mid,r-l,b-mid);c.beginPath();c.moveTo(l,b);for(let i=left;i<=right;i++)c.lineTo(x(i),yd(Math.max(0,-grid.elevation[row*grid.nx+i])));c.lineTo(r,b);c.closePath();c.fillStyle='#435c56';c.fill();line(c,Array.from({length:right-left+1},(_,n)=>[x(n+left),yd(Math.max(0,-grid.elevation[row*grid.nx+n+left]))]),'#91ac98',1);
 line(c,[[l,mid],[r,mid]],'#76929b77',.8,[3,4]);const pts=[];for(let i=left;i<=right;i++)if(grid.h[row*grid.nx+i])pts.push([x(i),mid-sampleFrame(row*grid.nx+i)/max*37]);line(c,pts,'#94e7e4',1.8);
 txt(c,'+'+max.toFixed(1)+' m',0,27,'#a1dfdf',9);txt(c,'0 m',10,mid+3,muted,9);txt(c,Math.round(depth)+' m',0,b,muted,9);const ix=g.index%grid.nx;line(c,[[x(ix),20],[x(ix),b]],'#f5d19a88',.8,[3,4]);txt(c,'STATION',Math.min(r-40,x(ix)+5),16,'#e9c995',8);
 for(let lon=-131;lon<=-123;lon+=2){const i=(lon-grid.lon0)/grid.step;if(i>=left&&i<=right)txt(c,Math.abs(lon)+'°W',x(i)-12,h-10,muted,9);}}
function draw(){drawMap();if(result){drawChart();drawSection();$('clock').textContent=formatTime(time);$('timeline').value=time;const g=selectedGauge(),v=sampleFrame(g.index);$('current').innerHTML=(v>=0?'+':'')+v.toFixed(2)+' <span>m</span>';}}
function setLayer(value){layer=value;document.querySelectorAll('[data-layer]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.layer===layer));$('legendTitle').textContent=layer==='source'?'FINAL SEAFLOOR MOTION · METERS':layer==='peak'?'PEAK |WATER LEVEL| · METERS':'WATER DISPLACEMENT · METERS';$('legendLow').textContent=layer==='source'?'≤ −10':layer==='peak'?'0':'≤ −4';$('legendMid').textContent=layer==='peak'?'3':'0';$('legendHigh').textContent=layer==='source'?'≥ +10':layer==='peak'?'≥ 6':'≥ +4';$('gradient').style.background=layer==='peak'?'linear-gradient(90deg,#132d3a,#b2675c,#ffd48c)':'';draw();}
async function workerSource(){if(workerURL)return workerURL;let model=$('model-code').textContent;if(!model.trim())model=await (await fetch('model.js')).text();const boot=`\nonmessage=function(e){try{const run=CascadiaModel.createRun(e.data.data,e.data.params,{factor:e.data.params.resolution==='fine'?1:2,dt:e.data.params.resolution==='fine'?2:4,sample:40});function go(){const done=run.advance(60);postMessage({type:'progress',value:run.solver.t/10800*100});if(done){const r=run.result(),transfers=r.frames.map(a=>a.buffer);postMessage({type:'result',result:r},transfers);}else setTimeout(go,0);}go();}catch(e){postMessage({type:'error',message:e.message});}};`;workerURL=URL.createObjectURL(new Blob([model,boot],{type:'text/javascript'}));return workerURL;}
async function runScenario(){const id=++runID;params=settings();labels();playing=false;$('play').textContent='▶ Play';$('play').disabled=true;$('progress').hidden=false;$('progressBar').value=0;$('progressText').textContent='Computing elastic seafloor deformation…';$('dirty').textContent='Computing scenario…';$('apply').disabled=true;if(worker)worker.terminate();
 const complete=r=>{if(id!==runID)return;result=r;time=firstRun?1200:0;firstRun=false;custom=null;$('progress').hidden=true;$('play').disabled=false;$('apply').disabled=false;$('dirty').textContent=JSON.stringify(settings())===JSON.stringify(params)?'Scenario up to date':'Changes pending — run to apply';const geo=r.geo;$('mapResolution').textContent='39°–52° N / '+(params.resolution==='fine'?'2′':'4′')+' MODEL GRID';$('resolutionStat').innerHTML=(params.resolution==='fine'?'2.3–2.9 × 3.7':'4.6–5.8 × 7.4')+' <span>km</span>';$('momentStat').innerHTML=(geo.moment/1e22).toFixed(2)+' × 10²² <span>N·m</span>';$('slipStat').innerHTML=geo.meanSlip.toFixed(1)+' / '+geo.maxSlip.toFixed(1)+' <span>m</span>';$('durationStat').innerHTML=(geo.duration/60).toFixed(1)+' <span>min</span>';$('patchStat').textContent=geo.faults.length+' rectangular fault patches · '+geo.length/1000+' km';$('diagnostics').textContent=`Run diagnostics: CFL ${r.cfl.toFixed(3)} (below the 0.9 guard), ${r.grid.nx} × ${r.grid.ny} cells, ${r.frames.length} snapshots. Largest |η|/depth anywhere: ${(r.maxRatio*100).toFixed(1)}%. ${r.maxRatio>.1?'This exceeds 10% in some shallow cells, where the linear approximation is weak.':'Small-amplitude assumptions remain a separate limitation.'}`;$('modelWarning').hidden=r.maxRatio<=.1;$('modelWarning').textContent=r.maxRatio>1?'Model limit exceeded: some shallow cells have displacements greater than their water depth. Those amplitudes are nonphysical in this linear model; this scenario cannot support local hazard estimates.':'Linear-model limit: some shallow cells exceed 10% displacement relative to depth (maximum '+(r.maxRatio*100).toFixed(0)+'%). Amplitudes in those cells are qualitative. Select a deeper offshore point to inspect regional propagation.';updateStations();updateSummary();draw();window.dispatchEvent(new Event('modelready'));};
 try{worker=new Worker(await workerSource());worker.onmessage=e=>{if(id!==runID)return;const d=e.data;if(d.type==='progress'){$('progressBar').value=d.value;$('progressText').textContent=`Propagating waves · ${Math.round(d.value)}% of three hours`;}if(d.type==='result'){worker.terminate();worker=null;complete(d.result);}if(d.type==='error')fail(d.message);};worker.onerror=e=>fail(e.message);worker.postMessage({data:D,params});}
 catch(e){ // Local multi-file browser security can block worker source fetch. Keep the standalone app usable.
  try{const run=M.createRun(D,params,{factor:params.resolution==='fine'?1:2,dt:params.resolution==='fine'?2:4,sample:40});function chunk(){if(id!==runID)return;const done=run.advance(35);$('progressBar').value=run.solver.t/10800*100;if(done)complete(run.result());else setTimeout(chunk,0);}chunk();}catch(err){fail(err.message);}
 }
 function fail(message){if(id!==runID)return;$('progressText').textContent='Model could not complete: '+message;$('dirty').textContent='Adjust the scenario and retry.';$('apply').disabled=false;}
}
formIDs.forEach(id=>$(id).addEventListener('input',()=>{labels();$('dirty').textContent='Changes pending — run to apply';document.querySelectorAll('[data-preset]').forEach(b=>b.classList.remove('active'));}));$('apply').onclick=runScenario;
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{$('segment').value=b.dataset.preset;$('magnitude').value=b.dataset.preset==='full'?9:8.7;$('slip').value='tapered';$('hypocenter').value=50;document.querySelectorAll('[data-preset]').forEach(x=>x.classList.toggle('active',x===b));runScenario();});
document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>setLayer(b.dataset.layer));$('play').onclick=()=>{if(!result)return;if(time>=result.end)time=0;playing=!playing;$('play').textContent=playing?'Ⅱ Pause':'▶ Play';};$('reset').onclick=()=>{playing=false;time=0;$('play').textContent='▶ Play';draw();};$('timeline').oninput=()=>{time=+$('timeline').value;draw();};
$('zoomIn').onclick=()=>{zoom=Math.min(4,zoom*1.3);drawMap();};$('zoomOut').onclick=()=>{zoom=Math.max(.75,zoom/1.3);drawMap();};$('home').onclick=()=>{zoom=1;panX=panY=0;drawMap();};
$('map').addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.75,Math.min(4,zoom*(e.deltaY>0?.92:1.08)));drawMap();},{passive:false});
$('map').onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,px:panX,py:panY,moved:false};$('map').setPointerCapture(e.pointerId);};$('map').onpointermove=e=>{const r=$('map').getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved=drag.moved||Math.hypot(dx,dy)>5;panX=drag.px+dx;panY=drag.py+dy;drawMap();}if(result&&view){const lon=(x-view.cx)/(view.s*.7)-127.05,lat=45.65-(y-view.cy)/view.s,k=pointIndex(lon,lat);$('cursorInfo').textContent=k===null?'':`${lat.toFixed(2)}°N  ${Math.abs(lon).toFixed(2)}°W  ·  ${layer==='source'?result.deformation[k].toFixed(2)+' m final seafloor motion':result.grid.h[k]?(layer==='peak'?result.peaks[k].toFixed(2)+' m peak':sampleFrame(k).toFixed(2)+' m now')+' · depth '+Math.round(result.grid.h[k])+' m':'land / masked shallows'}`;}};
function pointIndex(lon,lat){const g=result.grid,i=Math.round((lon-g.lon0)/g.step),j=Math.round((lat-g.lat0)/g.step);return i<0||i>=g.nx||j<0||j>=g.ny?null:j*g.nx+i;}
$('map').onpointerup=e=>{if(drag&&!drag.moved&&result){const r=$('map').getBoundingClientRect(),lon=(e.clientX-r.left-view.cx)/(view.s*.7)-127.05,lat=45.65-(e.clientY-r.top-view.cy)/view.s;let near=-1;result.gauges.forEach((g,i)=>{if(Math.hypot((lon-g.lon)*.7,lat-g.lat)*view.s<14)near=i;});if(near>=0){selected=near;custom=null;}else{const index=pointIndex(lon,lat);if(index!==null&&result.grid.h[index])custom={id:'custom',name:'Your ocean point',index,lon:result.grid.lon0+index%result.grid.nx*result.grid.step,lat:result.grid.lat0+Math.floor(index/result.grid.nx)*result.grid.step,depth:result.grid.h[index]};}updateStations();updateSummary();draw();}drag=null;};$('map').onpointercancel=()=>drag=null;
$('export').onclick=()=>{if(!result)return;const rows=['# Cascadia Lab 2.0: educational regional simulation, not an inundation forecast','# Scenario: '+JSON.stringify(params),'# Data: NOAA ETOPO 2022 and archived NOAA SIFT patch geometry. Fixed shoreline linear model, grid '+result.grid.step*60+' arc-minutes.',...result.gauges.map(g=>`# ${g.name}: ${g.lat.toFixed(5)} N, ${g.lon.toFixed(5)} E, depth ${g.depth.toFixed(2)} m; peak ${result.peaks[g.index].toFixed(6)} m; first |eta|>=0.1 m at ${result.arrivals[g.index]} s (includes source motion)`),'seconds,'+result.gauges.map(g=>g.name.replaceAll(' ','_')+'_eta_m').join(',')];for(let i=0;i<result.series[0].length;i++)rows.push(i*result.sample+','+result.series.map(s=>s[i].toFixed(6)).join(','));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download='CascadiaLab-v2-'+params.segment+'-M'+params.magnitude+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
window.addEventListener('resize',draw);document.querySelector('a[href="#science"]').onclick=()=>{$('science').open=true;};
function tick(now){const delta=last?Math.min(.15,(now-last)/1000):0;last=now;if(playing&&result){time=Math.min(result.end,time+delta*+$('speed').value);if(now-lastDraw>45){draw();lastDraw=now;}if(time>=result.end){playing=false;$('play').textContent='▶ Play';}}requestAnimationFrame(tick);}
initTerrain();drawMap();labels();runScenario();requestAnimationFrame(tick);
window.CascadiaLab={get result(){return result;},get params(){return params;},get time(){return time;},get selected(){return selected;},get layer(){return layer;},get zoom(){return zoom;}};
