'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),M=require('./model.js'),D=require('./data.js');
const defaults={segment:'full',magnitude:9,hypocenter:50,ruptureSpeed:2.5,rise:60,slip:'tapered'};
const reports={version:'2.0',date:'2026-09-05',checks:[]};
let maxRef=0;for(const q of require('./okada-reference.json'))maxRef=Math.max(maxRef,Math.abs(M.okada(D.faults.find(f=>f.name===q.fault),q.lon,q.lat)-q.value));assert(maxRef<1e-9);reports.checks.push({name:'Okada versus 27 original GeoClaw values',maximumAbsoluteErrorMeters:maxRef});
for(const segment of ['full','north','south'])for(const slip of ['uniform','tapered','shallow']){const g=M.scenario(D,{...defaults,segment,slip}),mo=g.faults.reduce((m,f)=>m+g.mu*f.length*f.width*f.slip,0);assert(Math.abs(mo/g.moment-1)<1e-12);}reports.checks.push({name:'Moment conservation',cases:9,toleranceRelative:1e-12});
const realGrid=M.gridFrom(D);const still=new M.Solver(realGrid);for(let i=0;i<100;i++)still.advanceStep();assert(still.eta.every(v=>v===0));assert(still.u.every(v=>v===0));reports.checks.push({name:'Still ocean over variable bathymetry',exactEquilibrium:true});
function uniformGrid(nx,ny,step,depth){return{nx,ny,step,lon0:0,lat0:-(ny-1)*step/2,h:new Float64Array(nx*ny).fill(depth)};}
const sg=uniformGrid(100,3,.01,2000),s=new M.Solver(sg,{dt:1,sponge:false}),k=Math.PI/(100*M.LM*.01);for(let j=0;j<3;j++)for(let i=0;i<100;i++)s.eta[j*100+i]=Math.cos(k*(i+.5)*M.LM*.01);
for(let i=0;i<500;i++)s.advanceStep();let sum=0,base=0;for(let i=0;i<100;i++){const exact=Math.cos(k*(i+.5)*M.LM*.01)*Math.cos(Math.sqrt(M.G*2000)*k*500);sum+=(s.eta[100+i]-exact)**2;base+=exact**2;}const relativeL2=Math.sqrt(sum/base);assert(relativeL2<.01);reports.checks.push({name:'Analytical constant-depth standing wave after 500 s',relativeL2Error:relativeL2});
const volume=new M.Solver(uniformGrid(80,40,.03,2000),{dt:2,sponge:false});for(let j=0;j<40;j++)for(let i=0;i<80;i++)volume.eta[j*80+i]=Math.exp(-((i-40)**2+(j-20)**2)/60);const v0=volume.volume();for(let n=0;n<600;n++)volume.advanceStep();const volumeError=Math.abs(volume.volume()/v0-1);assert(volumeError<1e-11);reports.checks.push({name:'Closed-basin volume conservation after 1200 s',relativeError:volumeError});
function sim(p,opt){const run=M.createRun(D,p,opt);while(!run.advance(200)){}assert(run.solver.eta.every(Number.isFinite));assert(run.solver.u.every(Number.isFinite));assert(run.solver.v.every(Number.isFinite));const r=run.result();assert(r.frames.every(f=>f.every(Number.isFinite)));assert(r.peaks.every(Number.isFinite));assert(r.cfl<.9);return r;}
const coarse=sim(defaults,{end:3600}),halfdt=sim(defaults,{end:3600,dt:2});const timeSensitivity=coarse.gauges.map((g,i)=>({station:g.name,peakDt4:coarse.peaks[g.index],peakDt2:halfdt.peaks[g.index],relativeDifference:Math.abs(coarse.peaks[g.index]/halfdt.peaks[g.index]-1)}));assert(timeSensitivity.every(g=>g.relativeDifference<.06));reports.checks.push({name:'Time-step sensitivity at 6 fixed offshore cells over 60 minutes',stations:timeSensitivity});
const fine=sim(defaults,{end:3600,dt:2,factor:1});function bilinearPeak(r,lon,lat){const g=r.grid,x=(lon-g.lon0)/g.step,y=(lat-g.lat0)/g.step,i=Math.floor(x),j=Math.floor(y),fx=x-i,fy=y-j;let peak=0;for(let n=0;n<r.frames.length;n++){const f=r.frames[n],v=(f[j*g.nx+i]*(1-fx)*(1-fy)+f[j*g.nx+i+1]*fx*(1-fy)+f[(j+1)*g.nx+i]*(1-fx)*fy+f[(j+1)*g.nx+i+1]*fx*fy)*r.frameScales[n];peak=Math.max(peak,Math.abs(v));}return peak;}
const resolution=coarse.gauges.map((g,i)=>{const peakCoarse=Math.max(...coarse.series[i].map(Math.abs)),peakFine=bilinearPeak(fine,g.lon,g.lat);return{station:g.name,latitude:g.lat,longitude:g.lon,peak4Arcmin:peakCoarse,peak2Arcmin:peakFine,relativeDifference:Math.abs(peakCoarse/peakFine-1)};});reports.checks.push({name:'Spatial sensitivity: 4 arcmin vs 2 arcmin at co-located interpolated stations, first hour only; diagnostic, not a convergence claim',stations:resolution});
for(const segment of ['full','north','south']){const r=sim({...defaults,segment,magnitude:9.2,slip:'shallow',rise:30,hypocenter:0,ruptureSpeed:3},{end:10800});assert(r.peaks.every(v=>v<200));}const fineExtreme=sim({...defaults,magnitude:9.2,slip:'shallow',rise:30,hypocenter:100},{factor:1,dt:2,end:10800,sample:40});assert(fineExtreme.maxRatio>0);reports.checks.push({name:'Fine-grid extreme scenario over three hours',cfl:fineExtreme.cfl,maximumDisplacementDepthRatio:fineExtreme.maxRatio});reports.checks.push({name:'Three-hour extreme scenarios remain finite',cases:3,magnitude:9.2,note:'Finite numerical output does not imply small-amplitude physics remains valid.'});
if(process.argv.includes('--report'))fs.writeFileSync(__dirname+'/validation.json',JSON.stringify(reports,null,2));console.log(JSON.stringify(reports,null,2));
